### ISSUE TITLE
Duplicate definition for tet Eri

### ISSUE THREAD

**Issue by LukeCEL** [ajtribick/celestia-gaia-stardb#3]
The latest output has two definitions for HIP 13847, which corresponds to two stars in Celestia, overlaid right on top of each other. As far as I know this is the only star defined twice. There may be others.

**Comment by ajtribick** [comment]
I think I see the issue here: if I look in the ASCC, there are two entries which have the HIP value 13847, with different TYC ids: TYC 7563-1016-1 (θ¹ Eri) and TYC 7563-1017-1 (θ² Eri).

The parsing code is prepared to handle cases in ASCC where there are multiple entries for a given TYC identifier but I'm not handling multiple TYC identifiers mapped to the same HIP identifier. Probably can be fixed using the same rule I'm using for the first case: take the alphabetically-earliest component identifier (ASCC column d3) as the correct match, which in this case would be θ¹.

Will have to run some tests to make sure, hopefully can create a fix soon.

**Comment by ajtribick** [comment]
On second look, I'm not even using the HIP identifier from the ASCC, so it's something else.

**Comment by ajtribick** [comment]
Found it: this is being produced by the SAO crossmatch. Forgot to take account of potential duplicates.
